### ISSUE TITLE
chap1 ex3: why set b = -6?

### ISSUE THREAD

**Issue by benx13** [TimotheeChauvin/NNDL-solutions#1]
Why did you chose the bais as -6

**Comment by ghost** [comment]
In the beginning of the argument, I start with a weight of 1 and a bias of -0.5 so the sigmoid is centered around x = 0.5. Then I multiply the argument of the sigmoid by a large enough value (12) to make the slope steeper. This means that the final bias is -0.5 x 12 = -6. As a result, the sigmoid remains centered around x = 0.5, which is a necessary feature.

I've updated the notebook to hopefully make it clearer :)
